tasks: {24: "<!DOCTYPE html>\r\n<html lang=\"ru\">\r\n    <head>\t\t\r\n\r\n\r\n<meta\
    \ http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\" />\r\n<title>\u041A\
    \u0432\u0435\u0441\u0442 - \u0430\u043A\u0442\u0438\u0432\u043D\u044B\u0435 \u044D\
    \u043A\u0441\u0442\u0440\u0435\u043C\u0430\u043B\u044C\u043D\u044B\u0435 \u0438\
    \ \u0438\u043D\u0442\u0435\u043B\u043B\u0435\u043A\u0442\u0443\u0430\u043B\u044C\
    \u043D\u044B\u0435 \u0438\u0433\u0440\u044B</title>\r\n<meta content=\"\" name=\"\
    description\" />\r\n<meta name=\"keywords\" content=\"\u043A\u0432\u0435\u0441\
    \u0442, \u0430\u0432\u0442\u043E\u043A\u0432\u0435\u0441\u0442, \u0430\u0432\u0442\
    \u043E\u043A\u0432\u0435\u0441\u0442\u044B, \u0432\u0435\u043B\u043E\u043A\u0432\
    \u0435\u0441\u0442\u044B, \u043F\u0435\u0448\u0435\u0445\u043E\u0434\u043D\u044B\
    \u0439 \u043A\u0432\u0435\u0441\u0442, \u043E\u043D\u043B\u0430\u0439\u043D \u043A\
    \u0432\u0435\u0441\u0442, \u0432\u0435\u043B\u043E \u043A\u0432\u0435\u0441\u0442\
    , \u0430\u0434\u0440\u0435\u043D\u0430\u043B\u0438\u043D, \u0434\u0440\u0430\u0439\
    \u0432, \u044D\u043A\u0441\u0442\u0440\u0438\u043C, \u0440\u0438\u0441\u043A,\
    \ \u0438\u0433\u0440\u0430, \u0438\u0433\u0440\u044B, \u0438\u043D\u0442\u0435\
    \u043B\u043B\u0435\u043A\u0442, quest, autoquest\" />\r\n<link rel=\"shortcut\
    \ icon\" href=\"http://cdn.endata.cx/images/questua/favicon.ico\" />\r\n<meta\
    \ name=\"viewport\" content=\"width=device-width, minimum-scale=1.0, maximum-scale=1.0\"\
    >\r\n\r\n\r\n<link href=\"http://quest.ua/css/v2/qu/cons/mobile.css?ver=1.43.2.1\"\
    \ type=\"text/css\" rel=\"stylesheet\" media=\"screen,projection\"  />\r\n<script\
    \ type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js\"\
    ></script>\r\n<script type=\"text/javascript\" src=\"http://quest.ua/js/v2/cons/main.js?ver=1.43.2.1\"\
    ></script>\r\n<script type=\"text/javascript\" src=\"http://quest.ua/js/v2/cons/engine.js?ver=1.43.2.1\"\
    ></script>\r\n<script type=\"text/javascript\" src=\"http://quest.ua/js/v2/jQuery/jquery.cookie.js?ver=1.43.2.1\"\
    ></script>\r\n<script type=\"text/javascript\">\r\n\t//<![CDATA[\r\n\tvar _gaq\
    \ = _gaq || []; try { _gaq.push(['t0._setAccount', 'UA-1064087-1']);  _gaq.push(['t0._trackPageview']);\
    \  _gaq.push(['t0._trackPageLoadTime'])  } catch(err) {} try { _gaq.push(['t1._setAccount',\
    \ 'UA-5421169-1']);  _gaq.push(['t1._trackPageview']);  _gaq.push(['t1._trackPageLoadTime'])\
    \  } catch(err) {} \r\n\t//]]>\r\n</script>\r\n<!--[if lt IE 9]>\r\n    <link\
    \ rel=\"stylesheet\" type=\"text/css\" href=\"http://quest.ua/css/v2/qu/mobile/ie.css\"\
    \ />\r\n<![endif]-->\r\n\r\n<script type=\"text/javascript\">\r\n\twindow.AjaxHelper\
    \ = new AjaxHelperClass('\u0417\u0430\u0433\u0440\u0443\u0437\u043A\u0430...');\r\
    \n</script>\r\n        \r\n\t\r\n\r\n\t<link href=\"http://quest.ua/css/v2/qu/mobile/gameengine.css?ver=1.43.2.1\"\
    \ type=\"text/css\" rel=\"stylesheet\" media=\"screen,projection\"  />\r\n<script\
    \ type=\"text/javascript\">\r\n\t//<![CDATA[\r\n\tvar _gaq = _gaq || []; try {\
    \ _gaq.push(['t0._setAccount', 'UA-1064087-1']);  _gaq.push(['t0._trackPageview']);\
    \  _gaq.push(['t0._trackPageLoadTime'])  } catch(err) {} try { _gaq.push(['t1._setAccount',\
    \ 'UA-5421169-1']);  _gaq.push(['t1._trackPageview']);  _gaq.push(['t1._trackPageLoadTime'])\
    \  } catch(err) {} \r\n\t//]]>\r\n</script>\r\n\r\n        \r\n    </head>\r\n\
    \    \r\n\r\n\r\n\r\n\r\n\r\n<body class=\"engine\">\r\n\t<script type=\"text/javascript\"\
    >\r\n\t/* <![CDATA[ */\t\r\n\t\t$(function() {\r\n\t\t\tvar $ctrlToFocus = $('#Answer');\r\
    \n\t\t\tif ($ctrlToFocus.length > 0)\r\n\t\t\t\t$ctrlToFocus.selectRange(0, $ctrlToFocus.val().length);\r\
    \n\t\t});\r\n\t/* ]]> */\r\n\t</script>\r\n\r\n\t<div class=\"header\">\r\n\t\t\
    <a href=\"/\" class=\"logo\"><img src=\"http://cdn.endata.cx/images/v2/qu/mobile/encounter.png\"\
    \ width=\"60\" height=\"60\" title=\"\u041A\u0432\u0435\u0441\u0442 - \u0430\u043A\
    \u0442\u0438\u0432\u043D\u044B\u0435 \u044D\u043A\u0441\u0442\u0440\u0435\u043C\
    \u0430\u043B\u044C\u043D\u044B\u0435 \u0438 \u0438\u043D\u0442\u0435\u043B\u043B\
    \u0435\u043A\u0442\u0443\u0430\u043B\u044C\u043D\u044B\u0435 \u0438\u0433\u0440\
    \u044B\" alt=\"\u041A\u0432\u0435\u0441\u0442 - \u0430\u043A\u0442\u0438\u0432\
    \u043D\u044B\u0435 \u044D\u043A\u0441\u0442\u0440\u0435\u043C\u0430\u043B\u044C\
    \u043D\u044B\u0435 \u0438 \u0438\u043D\u0442\u0435\u043B\u043B\u0435\u043A\u0442\
    \u0443\u0430\u043B\u044C\u043D\u044B\u0435 \u0438\u0433\u0440\u044B\"></a>\t\t\
    \r\n\t\t<div class=\"engine-nav\">\t\t\t\t\t\r\n\t\t\t<a href=\"/gamestatistics/places/23723/\"\
    \ target=\"_blank\" class=\"stats\" title=\"\u0421\u0442\u0430\u0442\u0438\u0441\
    \u0442\u0438\u043A\u0430\"></a>\r\n\t\t\t<a href=\"/gameengines/encounter/play/23723/?rnd=0,753398097005393\"\
    \ class=\"refresh\" title=\"\u041E\u0431\u043D\u043E\u0432\u0438\u0442\u044C\"\
    ></a>\r\n\t\t</div>\t\r\n\t</div><!--/header-->\r\n\t<div class=\"content\">\r\
    \n\t\t<div class=\"gametitle\">\r\n\t\t\t<h1><img src=\"http://cdn.endata.cx/images/v2/qu/engines/types/type0.gif\"\
    \ class=\"gametype\" width=\"30\" height=\"30\" title=\"\u041A\u0432\u0435\u0441\
    \u0442\" alt=\"\u041A\u0432\u0435\u0441\u0442\" /><a href=\"/games/details/23723/\"\
    >\u0414\u0435\u043C\u043E-\u0438\u0433\u0440\u0430 \u0434\u043B\u044F \u043D\u043E\
    \u0432\u0438\u0447\u043A\u043E\u0432</a></h1>\r\n\t\t</div>\r\n\t\t<div class=\"\
    spacer\"></div>\r\n\r\n\t\r\n\t\t\t<form method=\"post\">\t\t\r\n\t\t\t\t<input\
    \ type=\"hidden\" name=\"LevelId\" value=\"976562\" />\r\n\t\t\t\t<input type=\"\
    hidden\" name=\"LevelNumber\" value=\"24\" />\r\n\t\t\t\t<input type=\"text\"\
    \ id=\"Answer\" name=\"LevelAction.Answer\" maxlength=\"4000\" tabindex=\"1\"\
    \ value=\"\" />\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t<input type=\"submit\" class=\"submit\"\
    \ value =\"&gt;&gt;\" />\r\n\t  \r\n\t\t\t\t<label for=\"Answer\">\u0412\u0432\
    \u0435\u0434\u0438\u0442\u0435 \u043E\u0442\u0432\u0435\u0442 \u0438\u043B\u0438\
    \ \u043A\u043E\u0434</label>\t\r\n\t\t\t</form>\r\n\t\t<h2>\u0423\u0440\u043E\u0432\
    \u0435\u043D\u044C <span>24</span> \u0438\u0437 24</h2>\r\n\r\n\t\r\n\r\n\t\t\
    \ \r\n\r\n\t\r\n\t\t\t<h3 class=\"color_correct\">\r\n\t\t\t\t\u0411\u043E\u043D\
    \u0443\u0441 1\r\n\t\t\t\t<span class=\"color_sec\">(\u0432\u044B\u043F\u043E\u043B\
    \u043D\u0435\u043D)</span>\t\t\t\r\n\t\t\t</h3>\t\r\n\t\t\t<h3 class=\"color_bonus\"\
    > \r\n\t\t\t\u0411\u043E\u043D\u0443\u0441 2\r\n\t\t\t</h3>\r\n\t\t\t<h3 class=\"\
    color_bonus\"> \r\n\t\t\t\u0411\u043E\u043D\u0443\u0441 3\r\n\t\t\t</h3>\r\n\t\
    \t<div class=\"spacer\"></div>\r\n\t</div><!--/content-->\r\n\t<div class=\"footer\"\
    >\r\n\r\n<a href=\"http://dn.quest.ua/gameengines/encounter/play/23723/?id=23723&amp;level=24\"\
    \ onclick=\"mainSite();\">\u041F\u043E\u043B\u043D\u0430\u044F \u0432\u0435\u0440\
    \u0441\u0438\u044F</a>\r\n\t\r\n\t<br />&copy; <q>Quest</q>\r\n\t\r\n\r\n<!--\
    \ for nginx - if we don't set cookie 'mobile' to '0', nginx will redirect mobile\
    \ browsers from [domain_name] to m.[domain_name] -->\r\n<script type=\"text/javascript\"\
    >\r\n    function mainSite() {\r\n        var cookieDomain = document.location.host;\r\
    \n    \t\tvar wwwPrefix = 'www.';\r\n    \t\tif(cookieDomain.indexOf(wwwPrefix)\
    \ == 0) {\r\n    \t\t\tcookieDomain = cookieDomain.substr(wwwPrefix.length());\r\
    \n    \t\t}\r\n    \t\r\n        if (cookieDomain.indexOf('.') >= 0)\r\n\t\t\t\
    cookieDomain = cookieDomain.indexOf(\"m.\") == 0 ? cookieDomain.substr(1) : \"\
    .\" + cookieDomain;\r\n\r\n        $.cookie('mobile', '0', { path: \"/\", domain:\
    \ cookieDomain });\r\n    }\r\n</script>\t</div><!-- footer -->\r\n\r\n\r\n\r\n\
    \r\n\r\n<script type=\"text/javascript\">\r\n\t//<![CDATA[\r\n\t\r\n\t(function\
    \ () {\t\t\r\n\t\tvar ga = document.createElement('script'); ga.type = 'text/javascript';\
    \ ga.async = true;\r\n\t\tga.src = ('https:' == document.location.protocol ? 'https://ssl'\
    \ : 'http://www') + '.google-analytics.com/ga.js';\t\t\r\n\t\tvar s = document.getElementsByTagName('script')[0];\
    \ s.parentNode.insertBefore(ga, s);\r\n\t})();$.cookie('lang', 'ru', { expires:\
    \ 365, path: \"/\" });\r\n\t\t$.cookie('Domain', 'm.dn.quest.ua', { expires: 30,\
    \ path: \"/\" });\r\n\t//]]>\r\n</script>\r\n</body>\r\n</html>"}
