bot:
  answer-unknown: true
  commands: {approve: /approve, code: "/c /\u0441", codes: "/cc /\u0441\u0441 /\u0441\
      c /c\u0441", disapprove: /disapprove, edit: /edit, help: /help, info: /info,
    pause: /pause, reset: /reset, resume: /resume, save: /save, status: /status, stop: /stop}
  obfuscation_id: MTcwMzAyMTI3
  send-message-path: https://api.telegram.org/bot{key}/sendMessage
  token: 289812382:AAHK3XbAMWNZUxyCqqNL9TV2DVaZqhR1M_w
  updates-path: https://api.telegram.org/bot{key}/getUpdates?offset={offset}
game: {host: !!python/unicode 'online.quest.ua', id: !!python/unicode '32131', login: 'ZHJ1emhvY2hlaw==

    ', password: 'WW84OWthVDc=

    ', show_codes_left: 1 2 3 10, show_first_ap_time: true, show_time_left_minutes: 1
    5 10}
timeouts: {answer_check_interval: 1, max_attempts: 3, message_check_interval: 1, process_check_interval: 1,
  relogin_interval: 5}
