bot:
  answer-forbidden: false
  answer-unknown: false
  commands: {add_admin: /addadmin, add_field: /addfield, add_kc: /addkc, approve: /approve, code: "/c /\u0441", codes: "/cc\
      \ /\u0441\u0441 /\u0441c /c\u0441", disapprove: /disapprove, edit: /edit, gap: /gap,
    help: /help, hints: /hints, info: /info, pause: /pause, reset: /reset, resume: /resume,
    save: /save, status: /status, stop: /stop, task: /task, cancel: /cancel}
  obfuscation_id: 'MTcwMzAyMTI3'
  send-message-path: https://api.telegram.org/bot{key}/sendMessage
  token: 289812382:AAHK3XbAMWNZUxyCqqNL9TV2DVaZqhR1M_w
  updates-path: https://api.telegram.org/bot{key}/getUpdates?offset={offset}
game: {host: !!python/unicode 'dn.quest.ua', id: !!python/unicode '23723', login: 'ZHJhZ2F0ZW1w

    ', password: 'WW84OWthVDc=

    ', show_codes_left: 1 2 3 10 20 50 100, show_first_ap_time: true, show_first_hint_time: true,
  show_time_left_minutes: 1 4 9, show_time_to_hint: false}
timeouts: {answer_check_interval: 1, max_attempts: 3, message_check_interval: 1, process_check_interval: 1,
  relogin_interval: 5}
