bot:
  token: 289812382:AAHK3XbAMWNZUxyCqqNL9TV2DVaZqhR1M_w
  updates-path: https://api.telegram.org/bot{key}/getUpdates?offset={offset}
  send-message-path: https://api.telegram.org/bot{key}/sendMessage
  answer-unknown: True
  obfuscation_id: MTcwMzAyMTI3
  commands:
    code: /c /с
    codes: /cc /сс /сc /cс
    approve: /approve
    disapprove: /disapprove
    reset: /reset
    pause: /pause
    resume: /resume
    stop: /stop
    edit: /edit
    status: /status
    info: /info
    help: /help
game:
  login: druzhochek
  password: Yo89kaT7
  host: dn.quest.ua
  id: 23723
timeouts:
  max_attempts: 5
  message_check_interval: 1
  answer_check_interval: 1
  max_attempts: 3
  process_check_interval: 1
  relogin_interval: 5
