bot:
  admin_passphrase: 'dmVyeXN0cm9uZ2FkbWlucGFzc3dvcmQ=

    '
  answer-forbidden: false
  answer-unknown: false
  approved_chat: -177724202
  autosave: true
  commands: {add_admin: /addadmin, add_field: /addfield, add_kc: /addkc, alert: /alert,
    approve: /approve, cancel: /cancel, clearadmin: /clearadmin, clearfield: /clearfield,
    clearkc: /clearkc, code: "/c /\u0441", codes: "/cc /\u0441\u0441 /\u0441c /c\u0441",
    delete_admin: /deleteadmin, delete_field: /deletefield, delete_kc: /deletekc,
    disapprove: /disapprove, edit: /edit, edit_admin_pass: /eap, edit_field_pass: /efp,
    edit_kc_pass: /ekp, gap: /gap, help: /help, hints: /hints, info: /info, message: /message,
    message_admin: /ma, message_field: /mf, message_kc: /mk, pause: /pause, reset: /reset,
    resume: /resume, save: /save, status: /status, stop: /stop, task: /task}
  field_ids: 'ks4KJpqvzgUvkUw=

    '
  field_passphrase: 'aWxvdmVkcmFnYQ==

    '
  kc_ids: 'kA==

    '
  kc_passphrase: 'YnJhaW5zdG9ybXRvZGF5

    '
  obfuscation_id: 'kc4KJpqv

    '
  paused: false
  send-message-path: https://api.telegram.org/bot{key}/sendMessage
  token: 289812382:AAHK3XbAMWNZUxyCqqNL9TV2DVaZqhR1M_w
  updates-path: https://api.telegram.org/bot{key}/getUpdates?offset={offset}
  users-path: https://api.telegram.org/bot{key}/getChat?chat_id={user_id}
game: {host: !!python/unicode 'dn.quest.ua', id: !!python/unicode '23723', login: 'ZHJhZ2F0ZW1w

    ', password: 'WW84OWthVDc=

    ', show_codes_left: 1 2 3 10 20 50 100, show_first_ap_time: true, show_first_hint_time: true,
  show_time_left_minutes: 1 4 9, show_time_to_hint: false}
timeouts: {answer_check_interval: 1, max_attempts: 3, message_check_interval: 1, process_check_interval: 1,
  relogin_interval: 5}
